star-citizen: add support for EAC
fufexan/nix-gaming pull request #226
Opened 2024-12-20 22:05 UTC by Misterio77

CIG has since fixed EAC, and it now works correctly under linux. More so, it is actually required for playing star citizen 4.0.

This PR adds a `disableEac` flag to make the disabling optional; some fixes to make it work; as well as making EAC be enabled by default.

2024-12-20 23:07 UTC, Misterio77 commented
Failure seems unrelated?

2024-12-21 09:04 UTC, fufexan approved these changes
Yes, failure is unrelated. This looks good to me, but I'll ping @LovingMelody as well.

2024-12-21 16:29 UTC, LovingMelody approved these changes

2024-12-21 16:30 UTC, LovingMelody commented
LGTM can make this default once it hits live.

2024-12-21 16:47 UTC, LovingMelody requested changes

2024-12-21 16:47 UTC, LovingMelody commented on pkgs/star-citizen/default.nix
> +  disableEac ? false,
This should be set to true for now, this hasn't landed on the PTU

2024-12-21 16:48 UTC, LovingMelody commented
Just saw that it was disabled by default, PR works properly but breaks current live

2024-12-21 20:10 UTC, fufexan commented
> Just saw that it was disabled by default, PR works properly but breaks current live

Does this mean we should hold off merging?

2024-12-22 03:33 UTC, LovingMelody commented
either EAC needs to be disabled by default or a hold would be my preference. I'm unsure how long the game devs are on holiday break.

2025-01-11 16:49 UTC, Misterio77 commented
Hey folks, sorry for the delay.

Just flipped the bool so that EAC is still disabled as default.

2025-01-11 16:51 UTC, LovingMelody approved these changes
Thank you for contributing

2025-01-11 16:53 UTC, Misterio77 commented
Woops sorry I fucked up my branch, just a sec

2025-01-11 16:55 UTC, Misterio77 commented
All good now!

2025-01-11 18:04 UTC, LovingMelody requested changes

2025-01-11 23:17 UTC, LovingMelody commented on pkgs/star-citizen/default.nix
> +    export WINEPREFIX="$(readlink -f ${location})"
Looking at the lug-helper discord, it looks like some are having problems with prefix's being symlinked, is that what this is for? I believe it would be better to simply adjust the path for location.

2025-02-18 14:26 UTC, fufexan commented
Forgot this for a while, is it ready for merging? Can EAC be enabled now?

2025-02-19 10:00 UTC, LovingMelody commented
Thanks for following up, this pr isn't ready for merging
EAC isnt default upstream yet and clean installs don't work due to readlink

2025-02-25 01:37 UTC, Misterio77 commented on pkgs/star-citizen/default.nix
> +    export WINEPREFIX="$(readlink -f ${location})"
>  some are having problems with prefix's being symlinked

Yep, that's basically it. EAC apparently hates it.

> This doesn't resolve into a path if the directory does not yet exist.

Maybe we can `mkdir -p` it first?

2025-02-25 01:39 UTC, Misterio77 commented
Hey all, sorry for the wait.

> EAC isnt default upstream

Isn't 4.0.1 the default build now? Or have they lifted the EAC requirement, perhaps?

> clean installs don't work due to readlink

I'll push a fix with the `mkdir -p` solution I mentioned. Let me know if you have any thoughts!

2025-02-25 12:51 UTC, Misterio77 commented
> EAC isn't enforced on live still, only the PTU.

Awesome. Should be alright to leave it disabled by default, then.

> This patch should fix this

That makes sense! Adding it right now.

2025-02-25 18:22 UTC, LovingMelody approved these changes

2025-02-26 06:47 UTC, fufexan approved these changes

2025-02-26 06:47 UTC, merged