Add basic DXVK builder and installer
fufexan/nix-gaming pull request #7
Opened 2021-12-14 11:16 UTC by MagicRB

Signed-off-by: Magic_RB <magic_rb@redalder.org>

The installer needs work, I'll get to it eventually

2021-12-14 18:54 UTC, fufexan requested changes
Overall looks good. Could you run `nixpkgs-fmt` over the files?

2021-12-14 18:54 UTC, fufexan commented on pkgs/default.nix
> +  dxvk-x64 = prev.callPackage ./dxvk { };
Please add these in alphabetical order.

2021-12-14 18:54 UTC, fufexan commented on pkgs/dxvk/default.nix
> +  # NIX_CFLAGS_COMPILE = "-I ${wineWowPackages.staging}/include/wine/windows";
Is this needed anymore?

2022-11-02 04:58 UTC, LunNova commented on pkgs/dxvk/installer.nix
> +  cp -v ${pkgsCross.mingwW64.windows.mcfgthreads}/bin/mcfgthread-12.dll "$WINEPREFIX/dosdevices/c:/windows/syswow64/"
Are these the right way around? On native windows Syswow64 contains the 32 bit DLLs and system32 the 64 bit ones, despite that sounding backwards.

AFAIC mingwW64 is for the 64bit ones so it shouldn't go in syswow64.

2022-11-02 04:59 UTC, LunNova commented
@MagicRB Are you still interested in this? If not I'd like to start with what you have and finish it up

2022-11-02 10:41 UTC, MagicRB commented
I am but i dont habe time for it, you can take it over. @LunNova

2022-12-04 19:59 UTC, fufexan commented
Finished in #42. Thank you both!

2022-12-04 19:59 UTC, closed without merging